<?php

/**
 * @file
 * Contains iq_stage_file_proxy.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function iq_stage_file_proxy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the iq_stage_file_proxy module.
    case 'help.page.iq_stage_file_proxy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Loads resources or generates URLs that target public:// from a defined HTTP origin') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_iq_scss_compiler_css_alter().
 *
 * This function intends to modify and expand relative URLs found inside CSS,
 * especially for the `background-image:` property so that file proxying works.
 */
function iq_stage_file_proxy_iq_scss_compiler_css_alter(&$css, $context) {
  $css = iq_stage_file_proxy__replace_background_image_relative_with_absolute_urls($css);
}

/**
 * Implements hook_pagedesigner_css_rendered_alter().
 *
 * This function intends to modify and expand relative URLs found inside CSS,
 * especially for the `background-image:` property so that file proxying works.
 */
function iq_stage_file_proxy_pagedesigner_css_rendered_alter(string &$css, array $context) {
  $css = iq_stage_file_proxy__replace_background_image_relative_with_absolute_urls($css);
}

/**
 * Replaces background-image:url relative with absolute URLs.
 */
function iq_stage_file_proxy__replace_background_image_relative_with_absolute_urls($css) {
  return preg_replace("#(background-image: *url\(['\"]?)/sites/default/files/#", "$1" . \Drupal::config('iq_stage_file_proxy.settings')->get('remote_instance') . '/sites/default/files/', $css);
}
